def change():
	print ("Ingresar gasto:")
	print ("23.75")
	print ("Dinero recibido:")
	print ("")
	print ("Vuelto")
	print ("")
	print ("Pesos:")
	print ("76")
	print ("Centavos:")
	print ("25")
change ()
